apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld
  namespace: default
  #annotations:
  #  #kubernetes.io/ingress.class: "istio"
  #  kubernetes.io/ingress.global-static-ip-name: "helloworld-staging-staticip"
spec:
  backend:
    serviceName: helloworld
    servicePort: 80
