apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: helloworld
  name: helloworld
  namespace: default
spec:
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - image: gcr.io/peinau-187709/helloworld:4919483e9b7ddcccf2b6f1286d16df6ca386b171
        name: helloworld
        ports:
        - containerPort: 80
